language: php

php:
- '7.2'
- '7.1'

env:
- TEST_SUITE=unit MAGENTO_EDITION=community MAGENTO_VERSION=^2.3
- TEST_SUITE=unit MAGENTO_EDITION=community MAGENTO_VERSION=^2.2

stages:
- qa
- test

cache:
  directories:
  - $HOME/.composer/cache

before_install:
- composer global require hirak/prestissimo
- composer config repositories.magento composer "https://repo.magento.com/"
install:
- composer create-project --repository=https://repo.magento.com/ magento/project-$MAGENTO_EDITION-edition:$MAGENTO_VERSION $HOME/magento
- cd $HOME/magento
- composer config repositories.app-search '{"type":"path","url":"'$TRAVIS_BUILD_DIR'"}'
- cat composer.json
- composer require "$TRAVIS_REPO_SLUG:dev-$TRAVIS_BRANCH@dev"
before_script: 
- cp $TRAVIS_BUILD_DIR/dev/tests/$TEST_SUITE/phpunit.xml.dist dev/tests/$TEST_SUITE
script: 
- vendor/bin/phpunit -c dev/tests/$TEST_SUITE/phpunit.xml.dist

jobs:
  include:
  - stage: qa
    name: phplint
    install: composer install -n --prefer-dist
    before_script:
    script: vendor/bin/phplint src
  - stage: qa
    name: phpcs
    install: composer install -n --prefer-dist
    before_script:
    script: vendor/bin/phpcs --standard=PSR12 --extensions=php src
  - stage: qa
    name: phpmd
    install: composer install -n --prefer-dist
    before_script:
    script: vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming,unusedcode --suffixes php
  - stage: test
    before_script:
    - bin/magento module:enable --all
    script:
    - bin/magento setup:di:compile
