version: "3.4"

services:

  mysql:
    image: mysql:5.7
    env_file:
    - ./dev/magento.env

  redis:
    image: redis:5

  magento:
    build:
      context: ./dev/images/magento
      target: magento
    volumes:
    - .:/var/www/app-search-module
    env_file:
    - ./dev/magento.env
    ports:
    - 8888:80
