version: 2.1

executors:
  php-72:
    docker:
    - image: thecodingmachine/php:7.2-v2-apache
    environment:
      PHP_EXTENSIONS: gd intl pdo_mysql xsl zip soap bcmath opcache
  php-71:
    docker:
    - image: thecodingmachine/php:7.1-v2-apache
    environment:
      PHP_EXTENSIONS: gd intl pdo_mysql xsl zip soap bcmath opcache

jobs:
  build:
    parameters:
      executor:
        type: executor
      magento_version:
        type: string
      magento_edition:
        type: string
        default: community
    executor: << parameters.executor >>
    steps:
    - checkout:
        path: repo
    - restore_cache:
        keys:
        - v1-dependencies-<< parameters.magento_edition >>-<< parameters.magento_version >>-{{ checksum "repo/composer.json" }}
    - run:
        name: Install Magento
        command: |
          composer create-project --repository=https://repo.magento.com/ magento/project-<< parameters.magento_edition >>-edition:<< parameters.magento_version >> magento
    - run:
        name: Install App Search extension
        command: |
          cd magento
          composer config repositories.app-search '{"type": "path", "url": "../repo"}'
          composer config "minimum-stability" dev
          composer require swiftype/swiftype-app-search-magento
    - run: ls -al magento/vendor/swiftype
    - save_cache:
        paths:
        - ~/.composer/cache/
        key: v1-dependencies-<< parameters.magento_edition >>-<< parameters.magento_version >>-{{ checksum "repo/composer.json" }}

workflows:
  php72-mage23:
    jobs:
    - build:
        executor: php-72
        magento_version: ^2.3
  php71-mage23:
    jobs:
    - build:
        executor: php-71
        magento_version: ^2.3
  php72-mage22:
    jobs:
    - build:
        executor: php-72
        magento_version: ^2.2
  php71-mage22:
    jobs:
    - build:
        executor: php-71
        magento_version: ^2.2
