version: 2.1

executors:
  php-72:
    docker:
    - image: circleci/php:7.2-browsers
  php-71:
    docker:
    - image: circleci/php:7.1-browsers

jobs:
  build:
    parameters:
      executor:
        type: executor
      magento_version:
        type: string
      magento_edition:
        type: string
        default: community
    executor: << parameters.executor >>
    steps:
    - restore_cache:
        keys:
        - v1-dependencies-<< parameters.magento_edition >>-<< parameters.magento_version >>{{ checksum "composer.json" }}
    - run: composer create-project --repository=https://repo.magento.com/ magento/project-<< parameters.magento_edition >>-edition:<< parameters.magento_version >> magento
    - run: cat magento/composer.json
    - save_cache:
        paths:
        - ~/.composer/cache/
        key: v1-dependencies-<< parameters.magento_edition >>-<< parameters.magento_version >>{{ checksum "composer.json" }}


workflows:
  php72-mage23:
    jobs:
    - build:
        executor: php-72
        magento_version: ^2.3
  php71-mage23:
    jobs:
    - build:
        executor: php-71
        magento_version: ^2.3
  php72-mage22:
    jobs:
    - build:
        executor: php-72
        magento_version: ^2.2
  php71-mage22:
    jobs:
    - build:
        executor: php-71
        magento_version: ^2.2
