version: 2.1

executors:
  php-72:
    docker:
    - image: thecodingmachine/php:7.2-v2-apache
    environment:
      PHP_EXTENSIONS: gd intl pdo_mysql xsl zip soap bcmath opcache
      PHP_INI_MEMORY_LIMIT: 2g
  php-71:
    docker:
    - image: thecodingmachine/php:7.1-v2-apache
    environment:
      PHP_EXTENSIONS: gd intl pdo_mysql xsl zip soap bcmath opcache
      PHP_INI_MEMORY_LIMIT: 2g

jobs:
  build:
    parameters:
      executor:
        type: executor
      magento_version:
        type: string
      magento_edition:
        type: string
        default: community
    executor: << parameters.executor >>
    steps:
    - checkout:
        path: repo
    - restore_cache:
        keys:
        - v1-dependencies-<< parameters.magento_edition >>-<< parameters.magento_version >>-{{ checksum "repo/composer.json" }}
    - run:
        name: Install Magento
        command: |
          composer create-project --repository=https://repo.magento.com/ magento/project-<< parameters.magento_edition >>-edition:<< parameters.magento_version >> magento
    - run:
        name: Install App Search extension
        command: |
          cd magento
          composer config repositories.app-search '{"type": "path", "url": "../repo"}'
          composer config "minimum-stability" dev
          composer require swiftype/swiftype-app-search-magento
    - save_cache:
        paths:
        - ~/.composer/cache/
        key: v1-dependencies-<< parameters.magento_edition >>-<< parameters.magento_version >>-{{ checksum "repo/composer.json" }}
    - persist_to_workspace:
        root: .
        paths:
        - .

  test-compile:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
    - attach_workspace:
        at: .
    - run: cd magento && bin/magento module:enable --all && bin/magento setup:di:compile

workflows:
  workflow:
    jobs:
    - build:
        name: Build [PHP 7.2][Magento 2.3]
        executor: php-72
        magento_version: ^2.3
    - test-compile:
        name: Test Compile [PHP 7.2][Magento 2.3]
        executor: php-72
        requires:
        - Build [PHP 7.2][Magento 2.3]
    - build:
        name: Build [PHP 7.1][Magento 2.3]
        executor: php-71
        magento_version: ^2.3
    - test-compile:
        name: Test Compile [PHP 7.1][Magento 2.3]
        executor: php-71
        requires:
        - Build [PHP 7.1][Magento 2.3]
    - build:
        name: Build [PHP 7.2][Magento 2.2]
        executor: php-72
        magento_version: ^2.2
    - test-compile:
        name: Test Compile [PHP 7.1][Magento 2.2]
        executor: php-72
        requires:
        - Build [PHP 7.2][Magento 2.2]
    - build:
        name: Build [PHP 7.1][Magento 2.2]
        executor: php-71
        magento_version: ^2.2
    - test-compile:
        name: Test Compile [PHP 7.1][Magento 2.2]
        executor: php-71
        requires:
        - Build [PHP 7.1][Magento 2.2]
