version: 2.1

executors:
  php:
    parameters:
      version:
        type: string
        default: "7.2"
    docker:
    - image: circleci/php:<< parameters.version >>-browsers

jobs:
  build:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
    - run: php -v

workflows:
  php72-mage23:
    jobs:
    - build:
        executor:
          name: php
          version: "7.2"

  php71-mage23:
    jobs:
    - build:
        executor:
          name: php
          version: "7.1"
